spring:
  application:
    name: hello-spring-cloud-admin

server:
  port: 8764

eureka:
  instance:
    hostname: localhost
    #设置心跳时间
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/